### ISSUE TITLE
Continuous Speech Listening not working

### ISSUE THREAD

**Issue by kyzylmonteiro** [EricBatlle/UnityAndroidSpeechRecognizer#1]
First of all, thank you for this repo, I was clueless about speech recognition on unity android before this. 

But I can not seem to get the continuous speech recognition working, even in the test apk it doesn't work. Any suggestions on what could be the issue?

And do you know if there is a way to get rid of the beeps when the recognition starts and stops?

**Comment by EricBatlle** [comment]
Glad to help!
Please attach more information on the issue or it's gonna be hard to find out why it's not working on your device.
Did you try to launch the apk and open ADB to check the logs? Which device are you using? etc

**Comment by kyzylmonteiro** [comment]
Hey, I had tried the test.apk on a couple of devices Xiaomi note 8 pro & A3, just to be clarify continuous speech recognition means the recognition doesn't stop when you take a pause right? that is it recognizes the speech as you speak in real-time right?
I haven't tried the ADB log, will read about it, and check the issue it shows! Thanks.

**Comment by EricBatlle** [comment]
No. "Continuous speech recognition" means: when the recognition ends, it will start again, automatically. What you want, if I'm not wrong, is to increase the time between pauses, could be that? 
In this case, you need to send an EXTRA information to the Recognizer Intent, in concrete, this: https://developer.android.com/reference/android/speech/RecognizerIntent#EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS ^^
