### ISSUE TITLE
Bluetooth Headset

### ISSUE THREAD

**Issue by woelfle2004** [EricBatlle/UnityAndroidSpeechRecognizer#10]
Hi,
I am just wondering if the UnityAndroidSpeechRecognizer is able to perform well on a bluetooth headset.
The voice command should come from the bluetooth microphone and the game's sound ond the headphones.
Is this possible with this plugin ?
many thanks
Rainer

**Comment by EricBatlle** [comment]
Hi Rainer,

It should work if the headset have an Android OS, the connection type should not be relevant, ping me if you try it!
