### ISSUE TITLE
Neither OnResult nor OnError are called 

### ISSUE THREAD

**Issue by gtop79** [EricBatlle/UnityAndroidSpeechRecognizer#12]
I desesperately try to make the application run on my mobile but no text is returned from my voice.

The methods below are never called:
public void OnResult(string recognizedResult)
public void OnError(string recognizedError)

I direclty installed the demo application on my phone. What did I miss?
Thanks a lot for your help.

**Comment by EricBatlle** [comment]
I need more information to help you @gtop79 .
Try to attach some logcats, the device that you're using, the permisions that your device has, which version of the plugin are you using, etc

**Comment by EricBatlle** [comment]
Since there haven't been any recent updates, I am going to close this issue.

@gtop79 if you're still experiencing this problem and want to continue the discussion just leave a comment here and I'll be happy to re-open this.
