### ISSUE TITLE
apk works but my build doesn't

### ISSUE THREAD

**Issue by ftmabt** [EricBatlle/UnityAndroidSpeechRecognizer#13]
the apk works on my device but my own build from the demo doesn't; like it doesn't record my voice. is there some unity setting for it? my device is xiaomi a3 and the app has microphone permission. 

also i have a question does it support persian language? (fa-IR)

**Comment by EricBatlle** [comment]
Hey @ftmhabt, thanks for using my plugin.
I need more details to know what is happening, do you have any android logcat to show to me? There's no extra setting that you need to set, just plug and play.

And yes, it supports persian language, you only need to call it like:
`plugin.StartListening(true, "fa");`

**Comment by ftmabt** [comment]
Hi @EricBatlle 
Thank you for the plugin and for answering!
sure here
![Screenshot 2023-05-05 195653](https://user-images.githubusercontent.com/130227790/236515235-75b37d19-1397-4e7c-875f-2f10a9a5f26e.png)

when i touch Start Listening button it says bind to recognition service failed.

**Comment by ftmabt** [comment]
I just added this line in AndroidManifest.xml and it works very well. thanks again!
`<queries>
        <package android:name="com.google.android.googlequicksearchbox"/>
</queries>`

**Comment by ftmabt** [comment]
sorry i keep coming back. i used your code for persian language but it still returns english words? i even replaced "en-US" with "fa" in all four scripts and removed language dropdown but it's still english.

**Comment by EricBatlle** [comment]
Try using "fa-IR" and let me know the results please

**Comment by ftmabt** [comment]
It worked. Thank you so much!! you're a lifesaver
