### ISSUE TITLE
Error: no selected voice recognition service

### ISSUE THREAD

**Issue by jhclaura** [EricBatlle/UnityAndroidSpeechRecognizer#18]
Thanks for the awesome plugin! I've tried it with phone before and it worked well.

Now I try to use it with Quest Pro, after solving some build errors e.g. `allowBackup="false"` conflict & `Execution failed for task ‘:launcher:checkReleaseDuplicateClasses’`, it finally built (yay!) but then I got this error:
`SpeechRecognizer: no selected voice recognition service` after `SpeechRecognizer: StartListeningCalled`

Does it mean it's not possible to use this Plugin with Quest?

**Comment by EricBatlle** [comment]
Hi @jhclaura I'm glad you find my plugin useful! :D

I don't have any Quest Pro to test why is giving you this error message, but after some digging you should check:
1. Does your Quest pro has the `[Google App](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&pli=1)`?
2. Does your Quest pro has internet connection?
3. Make sure that on the device you have selected a default speech recognizer (I'm not sure how to do that in Quest pro to be honest)

Finally, you can also try to force that by adding this code on the plugin: 
` sr = SpeechRecognizer.createSpeechRecognizer(getActivity(), ComponentName.unflattenFromString("com.google.android.googlequicksearchbox/com.google.android.voicesearch.serviceapi.GoogleRecognitionService"));
`

On line 111 in this file:
https://github.com/EricBatlle/UnityAndroidSpeechRecognizer/blob/master/UnitySpeechRecognizerPlugin/SpeechRecognizer/src/main/java/com/example/eric/unityspeechrecognizerplugin/SpeechRecognizerFragment.java

**Comment by jhclaura** [comment]
Thanks for all the suggestions Eric! After some searching:

1. No it hasn't and there's no Google App in Quest's App Store either
2. Yes it has internet connection
3. Yea I don't know either. Quest has settings for [Voice Command](https://www.meta.com/help/quest/articles/in-vr-experiences/oculus-features/using-voice-commands/) that's powered by its [Voice SDK](https://developer.oculus.com/documentation/unity/voice-sdk-overview/). Maybe that means it's not possible to get speech recognizer through Android route?

**Comment by EricBatlle** [comment]
@jhclaura did you tried to modify the plugin with the line of Code I posted?

**Comment by EricBatlle** [comment]
Since there haven't been any recent updates, I am going to close this issue.

@jhclaura if you're still experiencing this problem and want to continue the discussion just leave a comment here and I'll be happy to re-open this.
