### ISSUE TITLE
Neither onResults nor onError gets called when no audio is detected

### ISSUE THREAD

**Issue by MoElghobashy** [EricBatlle/UnityAndroidSpeechRecognizer#19]
What I'm doing is that I set a panel over the whole game when recording starts, and sets it off when the recording ends.
if no audio is detected at all, none of the methods gets invoked, and I don't know how to set the panel off in that case,

**Comment by EricBatlle** [comment]
Do you have continous recognition enabled?

**Comment by EricBatlle** [comment]
Since there haven't been any recent updates, I am going to close this issue.

@MoElghobashy  if you're still experiencing this problem and want to continue the discussion just leave a comment here and I'll be happy to re-open this.
