### ISSUE TITLE
Update to AndroidX packages required.

### ISSUE THREAD

**Issue by utkarshparasarampuria** [EricBatlle/UnityAndroidSpeechRecognizer#2]
Hi Eric, thanks for the plugin. It's the right one for my use case. I have an issue though, which will require you to update the plugin to solve.
The plugin works perfectly in a standalone Unity project, but causes issues when integrated in my project that uses other Android dependencies. This is because I have other 3rd party SDKs in my project that have the AndroidX dependencies.

This is from their [official documentation available here](https://developer.android.com/jetpack/androidx/migrate):
"AndroidX replaces the original support library APIs with packages in the androidx namespace. Only the package and Maven artifact names changed; class, method, and field names did not change."

To resolve this issue, you'll just need to replace the classes from android.support.v4.xxx to androidx.core.app.xxxx, and build the plugin.

I am sharing the [class mappings list](https://developer.android.com/jetpack/androidx/migrate/class-mappings#androidsupportv4) for the migration with you as well. Please update this plugin and it'll be a great help to me.
Thanks.

**Comment by EricBatlle** [comment]
Hi @utkarshparasarampuria, glad to help ^^

I've updated the plugin to fit AndroidX dependencies, you can check the new release [here](https://github.com/EricBatlle/UnityAndroidSpeechRecognizer/releases/tag/v1.1).

Remember to Star this repo if it was useful for you! 👍

**Comment by EricBatlle** [comment]
Hi @utkarshparasarampuria, do to the addition of your star on the repo, and the abscence of more comments I suppouse it works as it should, so I'll close this issue, feel free to reopen it or open a new one if something doesn't work :D
