### ISSUE TITLE
Version 1.2 doesn't work at the device where 1.1 works.

### ISSUE THREAD

**Issue by dyhmichail** [EricBatlle/UnityAndroidSpeechRecognizer#3]
I download version 1.1 on phone and all works perfectly.
But when I install the 1.2 version, the button Start recognize doesn't begin speech to text.

**Comment by EricBatlle** [comment]
> I download version 1.1 on phone and all works perfectly.
> But when I install the 1.2 version, the button Start recognize doesn't begin speech to text.

Hi @dyhmichail , thanks for your feedback, I've a question: did you uninstall the first version (1.1), before the second one (1.2)? 

Also if possible, try to attach your logcats, to debug what is happening :D

**Comment by EricBatlle** [comment]
Hi @dyhmichail , no news? If so, I'll close this issue in a few days, thanks.
