### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Tborth** [EricBatlle/UnityAndroidSpeechRecognizer#5]
You add the toggle button only click on anywhere click on it also not working it try your demo app

**Comment by EricBatlle** [comment]
Please improve your Issue description so I can help with it, thanks.

**Comment by Tborth** [comment]
I test your you add in the for demo v1.2
Only speechRecongnize_1.2.apk
It have toggle button issue ,I open in unity to figure out what the problem
don't solution

**Comment by EricBatlle** [comment]
Try to specify the resultant behaviour and the expected behaviour, also paste your logcats to track down the issue please.

**Comment by EricBatlle** [comment]
Since there haven't been any recent updates in the last 10 days here, I am going to close this issue.

@Tborth  if you're still experiencing this problem and want to continue the discussion just leave a comment here and I'll  be happy to re-open this.
