### ISSUE TITLE
HTC Vive Focus plus on VIU integration

### ISSUE THREAD

**Issue by alex798** [EricBatlle/UnityAndroidSpeechRecognizer#6]
Hi Eric,

We can't run Recognizer in vr experience.
It seems that the main issue is Manifest file- HTC needs :

activity android:name="com.htc.vr.unity.WVRUnityVRActivity" with
intent-filter
                action android:name="android.intent.action.MAIN"
                category android:name="android.intent.category.LAUNCHER"
                category android:name="com.htc.intent.category.VRAPP"
intent-filter

to run VR experience… And as far as I understand Recognizer needs them too(doesn’t it?)

Logcat shows no issues, downloaded 1.0 version of plug-in(because vive is 25 API level), Unity 2019.4.8f1, ViveWaveXRPlugin version 1.0.1, if U need any other info U can mail me(u have adress)... 

Will be very gratefull if U point the way to solve it(we need only start and stop listening function in our project)...

**Comment by EricBatlle** [comment]
Hi @alex798 ,

Sorry for the big delay, but I was on a business trip those days :( 
Did you solve your problem? Or still persists? 
Do you have any new info?

If you think that the problem could be related with some manifest troubles, I'll try to update version 1.0 to work similar to 1.2 which have a pretty empty AndroidManifest and only requires the RECORD_AUDIO permission, without of the MAIN and LAUNCHER activity if the non-AndroidX dependencies can work like that.

But if you have any new info, remember to post it please!

**Comment by alex798** [comment]
Hi @EricBatlle,

No problem, didn't work on issue after posting issue, so no new info...

Will try updated version as soon as U post it, thx.

**Comment by EricBatlle** [comment]
Hi @alex798 , 

Have been a while, but I didn't forget about your issue. 
I think that the new release of the plugin: [v.1.3.support](https://github.com/EricBatlle/UnityAndroidSpeechRecognizer/releases/tag/v1.3.support) will fix your problems if you haven't figure it out yet ^^

Tell me something when you can test it!

**Comment by alex798** [comment]
Good day,
Tested on Vive, but didn't get to make it work...

Have a couple of questions:
1)in Android_plugin
private string javaClassPackageName = "com.example.eric.unityspeechrecognizerplugin.SpeechRecognizerFragment";
but name of your document is ExampleInstrumentedTest.java - is it a typo or where am I wrong?

2)In AndroidManifest we use package="com.unity3d.player"> and U have package="com.example.eric.unityspeechrecognizerplugin"> - how to correctly merge those manifests?

3)I get that this package name is path to file, but how to point to this file if I need to use another manifest?

**Comment by EricBatlle** [comment]
hi @alex798 , are you sure that you have tried the 1.3.support version? 
Your project should auto-merge manifests without troubles, which message is throwing?

**Comment by EricBatlle** [comment]
> > hi @alex798 , are you sure that you have tried the 1.3.support version?
> > Your project should auto-merge manifests without troubles, which message is throwing?
> 
> Yes, sure about version... In that case is there a probability that your plugin uses some google libraries which Vive focus simply don't support? - I can send U my project folder to find any mismatches...

Plugin only uses **support-v4-24.1.1.aar** as extern library.


> Good day,
> Tested on Vive, but didn't get to make it work...
> 
> Have a couple of questions:
> 1)In AndroidManifest we use package="com.unity3d.player"> and U have package="com.example.eric.unityspeechrecognizerplugin"> - how to correctly merge those manifests?
> 
> 2)I get that this package name is path to file, but how to point to this file if I need to use another manifest?

1. This package name is the direction of where the plugin is stored on the android-java file, you don't really need to merge manually those android manifests. But in case you will, the only thing to keep in mind is to ensure that those lines are included:
```
<uses-permission android:name="android.permission.RECORD_AUDIO" />

    <uses-sdk
        android:minSdkVersion="24"
        android:targetSdkVersion="28" />

    <application
        android:allowBackup="true"
        android:supportsRtl="true">
    </application>
```
2. I don't really get the question sorry :(

And again, tell me which error message is throwing your app.

You can send me the link of your repo but I don't have any HTC Vive device to test it, it's a building error or a runtime one?

**Comment by alex798** [comment]
> 
> 
> > > hi @alex798 , are you sure that you have tried the 1.3.support version?
> > > Your project should auto-merge manifests without troubles, which message is throwing?
> > 
> > 
> > Yes, sure about version... In that case is there a probability that your plugin uses some google libraries which Vive focus simply don't support? - I can send U my project folder to find any mismatches...
> 
> Plugin only uses **support-v4-24.1.1.aar** as extern library.
> 
> > Good day,
> > Tested on Vive, but didn't get to make it work...
> > Have a couple of questions:
> > 1)In AndroidManifest we use package="com.unity3d.player"> and U have package="com.example.eric.unityspeechrecognizerplugin"> - how to correctly merge those manifests?
> > 2)I get that this package name is path to file, but how to point to this file if I need to use another manifest?
> 
>     1. This package name is the direction of where the plugin is stored on the android-java file, you don't really need to merge manually those android manifests. But in case you will, the only thing to keep in mind is to ensure that those lines are included:
> 
> 
> ```
> <uses-permission android:name="android.permission.RECORD_AUDIO" />
> 
>     <uses-sdk
>         android:minSdkVersion="24"
>         android:targetSdkVersion="28" />
> 
>     <application
>         android:allowBackup="true"
>         android:supportsRtl="true">
>     </application>
> ```
> 
>     1. I don't really get the question sorry :(
> 
> 
> And again, tell me which error message is throwing your app.
> 
> You can send me the link of your repo but I don't have any HTC Vive device to test it, it's a building error or a runtime one?

It's runtime one. and didn't get errors- just don't work...

My boss told me that app don't work on his android tablet(Huawei) and he suspects that it connects with blockade Huawei from google services(which probable do online recognition) - in that case it explains why vive don't work either- it doesn't have google services(according to boss)...

**Comment by EricBatlle** [comment]
> > > > hi @alex798 , are you sure that you have tried the 1.3.support version?
> > > > Your project should auto-merge manifests without troubles, which message is throwing?
> > > 
> > > 
> > > Yes, sure about version... In that case is there a probability that your plugin uses some google libraries which Vive focus simply don't support? - I can send U my project folder to find any mismatches...
> > 
> > 
> > Plugin only uses **support-v4-24.1.1.aar** as extern library.
> > > Good day,
> > > Tested on Vive, but didn't get to make it work...
> > > Have a couple of questions:
> > > 1)In AndroidManifest we use package="com.unity3d.player"> and U have package="com.example.eric.unityspeechrecognizerplugin"> - how to correctly merge those manifests?
> > > 2)I get that this package name is path to file, but how to point to this file if I need to use another manifest?
> > 
> > 
> > ```
> > 1. This package name is the direction of where the plugin is stored on the android-java file, you don't really need to merge manually those android manifests. But in case you will, the only thing to keep in mind is to ensure that those lines are included:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > <uses-permission android:name="android.permission.RECORD_AUDIO" />
> > 
> >     <uses-sdk
> >         android:minSdkVersion="24"
> >         android:targetSdkVersion="28" />
> > 
> >     <application
> >         android:allowBackup="true"
> >         android:supportsRtl="true">
> >     </application>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 1. I don't really get the question sorry :(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And again, tell me which error message is throwing your app.
> > You can send me the link of your repo but I don't have any HTC Vive device to test it, it's a building error or a runtime one?
> 
> It's runtime one. and didn't get errors- just don't work...
> 
> My boss told me that app don't work on his android tablet(Huawei) and he suspects that it connects with blockade Huawei from google services(which probable do online recognition) - in that case it explains why vive don't work either- it doesn't have google services(according to boss)...

Plugin performs the recognition through native android class Speech Recognizer: httpss://developer.android.com/reference/android/speech/SpeechRecognizer

So if the tablet of your boss can perform native recognition, plugin must work.

And if you don't have errors, attach logcats traces to see what's going on, otherwise it's really hard to help you :/

**Comment by EricBatlle** [comment]
Since there haven't been any recent updates, I am going to close this issue.

 @alex798  if you're still experiencing this problem and want to continue the discussion just leave a comment here and I'll be happy to re-open this.
