### ISSUE TITLE
Working with different languages?

### ISSUE THREAD

**Issue by 11Sheep** [EricBatlle/UnityAndroidSpeechRecognizer#7]
Hi,
Thanks for the plugin!
Can i set it to work with different languages?

**Comment by EricBatlle** [comment]
Hi @11Sheep, thank you for your words!

There is no call right now to change the language on the plugin, but I'll change that on a future update, I'll mark your petition as a Feature Request to add it on my roadmap.

**Comment by EricBatlle** [comment]
@11Sheep new Version 1.3 of the plugin allows you set different languages! :tada:
