### ISSUE TITLE
keep this library in proguard

### ISSUE THREAD

**Issue by truongluuxuan** [EricBatlle/UnityAndroidSpeechRecognizer#9]
this lib working in debug but it not working in my release. How to keep it in progurad

**Comment by EricBatlle** [comment]
Hi @truongluuxuan , this plugin is currently working on my releases, so I'm afraid that I'll need more información about your issue to help you.

Which version of the plugin are you using? What are your logcats printing? There's any trace of your own code? And attach all the relevant information please.

**Comment by EricBatlle** [comment]
Since there haven't been any recent updates, I am going to close this issue.

@truongluuxuan  if you're still experiencing this problem and want to continue the discussion just leave a comment here and I'll be happy to re-open this.
